swagger: '2.0'
info:
  description: 'First swagger'
  version: 1.0.0
  title: Swagger PostsStore
tags:
  - name: posts
    description: Everything about Posts
  - name: user
    description: Operations about User
schemes:
  - http
paths:
  /posts:
    get:
      tags:
      - posts
      summary: Get all posts
      consumes:
      - application/json
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/post'
        400:
          description: 'Bad request'
    post:
      tags:
      - posts
      summary: Add a new post
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Post object that needs to be added to the store
        required: true
        schema:
          type: object
          description: Post entity
          properties:
            title:
              type: string
            text:
              type: string
      responses:
        200:
          description: Success
        400:
          description: Invalid status value
  
  /posts/{postId}:
    get:
      tags:
      - posts
      summary: Get post by Id
      consumes:
      - application/json
      parameters:
      - name: postId
        in: path
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            items:
              $ref: '#/definitions/post'
        400:
          description: 'Invalid status value'
    delete:
      tags:
      - posts
      summary: Delete post
      consumes:
      - application/json
      parameters:
      - name: postId
        in: path
        required: true
        type: string
      responses:
        200:
          description: Success
        400:
          description: 'Invalid status value'
    put:
      tags:
        - posts
      summary: Update post
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: postId        
        required: true
        type: string
      - in: body
        name: body
        description: Post object that needs to be added to the store
        required: true
        schema:
          type: object
          description: Post entity
          properties:
            title:
              type: string
            text:
              type: string
      responses:
        200:
          description: Success
        400:
          description: Invalid status value
  /user:
    get:
      tags:
      - users
      summary: Get all users
      consumes:
      - application/json
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        400:
          description: 'Invalid status value'
  /user/{userId}:
    get:
      tags:
      -  users
      summary: Get user by id
      produces:
      -  application/json
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        400:
          description: 'Invalid status value'
    delete:
      tags:
      -  users
      summary: Delete user by id
      produces:
      -  application/json
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: Success
        400:
          description: 'Invalid status value'
    put:
      tags:
      - users
      summary: Update user info
      produces:
      - application/json
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      - in:  body
        name:  body
        description: User object for update
        required: true
        schema:
          type: object
          description: User entity
          properties:
            name:
              type: string
            mail:
              type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            items:
              $ref: '#/definitions/user'
        400:
          description: 'Invalid status value'
definitions:
  post:
   properties:
    postId:
      type: string
    userID:
      type: string
    title:
      type: string
    text:
      type: string
    createdAt:
      type: string
  user:
    properties:
      userId:
        type: string
      name:
        type: string
      mail:
        type: string
responses:
  success:
    description: success

